<?php
/**
 * @codingStandardsIgnoreFile
 * @codingStandardsIgnoreStart
 * @codingStandardsIgnoreEnd
 * @codingStandardsIgnoreLine
 * @codingStandardsChangeSetting
 */

/**
 * @codingStandardsIgnoreFile
 */

/**
 * @codingStandardsIgnoreStart
 */

/**
 * @codingStandardsIgnoreEnd
 */

/**
 * @codingStandardsIgnoreLine
 */

/**
 * @codingStandardsChangeSetting
 */

// @codingStandardsIgnoreFile
// @codingStandardsIgnoreStart
// @codingStandardsIgnoreEnd
// @codingStandardsIgnoreLine
// @codingStandardsChangeSetting

/* @codingStandardsIgnoreFile */
/* @codingStandardsIgnoreStart */
/* @codingStandardsIgnoreEnd */
/* @codingStandardsIgnoreLine */
/* @codingStandardsChangeSetting */
