<?php
/**
 * phpcs:ignoreFile
 * phpcs:disable
 * phpcs:enable
 * phpcs:ignore
 * phpcs:set
 */

/**
 * phpcs:ignoreFile
 */

/**
 * phpcs:disable
 */

/**
 * phpcs:enable
 */

/**
 * phpcs:ignore
 */

/**
 * phpcs:set
 */

// phpcs:ignoreFile
// phpcs:disable
// phpcs:enable
// phpcs:ignore
// phpcs:set

/* phpcs:ignoreFile */
/* phpcs:disable */
/* phpcs:enable */
/* phpcs:ignore */
/* phpcs:set */
