<?php

namespace ImportInternalFunction;

$array = range(1, 10);

$keys = array_keys($array);

$date = new Date();

$count = count($keys);
$count = $obj->count();
$count = $obj::count();

function myFunction() {
}

if (isset($x) || empty($x)) {
    unset($x);

    reset($keys);
}

$count = &count($array);
$count = \count($array);

$count = Count($array);

$keys = Array_Keys($array);
$values = Array_Rand($array);

$rand = mt_rand(1, 29);
$rand = \MT_rand(1, 100);
